download-db: 
	curl https://ftp.ncbi.nlm.nih.gov/pub/COG/COG2024/data/cog-24.def.tab --output data/latest/cog.def.tab
	curl https://ftp.ncbi.nlm.nih.gov/pub/COG/COG2024/data/cog-24.fun.tab --output data/latest/cog.fun.tab
	curl https://ftp.ncbi.nlm.nih.gov/pub/COG/COG2024/data/cog-24.pathways.tab --output data/latest/cog.pathways.tab