name: The Clusters of Orthologous Genes (COG) database
description: A database of orthologous gene clusters used for functional annotation and comparative genomics.
link: https://www.ncbi.nlm.nih.gov/research/cog-project/